#!/bin/bash

traduccion(){
	case $1 in
		1)
			echo lunes
		;;
		2)
			echo martes
		;;
		3)
			echo miercoles
		;;
		4)
			echo jueves
		;;
		5)
			echo viernes
		;;
		6)
			echo sabado
		;;
		7)
			echo domingo
		;;
	esac
}

mensaje_ayuda(){
	echo "Para mejorar el script que ya hizo, el influencer del ejercicio 2 decide agregar una nueva
	funcionalidad a su script: monitoreo de directorios en tiempo real.
	Implementar sobre el script del ejercicio anterior un mecanismo que permite renombrar los archivos a
	medida que se vayan copiando/moviendo/creando en el directorio de las fotos. Esto se debe realizar
	utilizando un demonio.
	Tener en cuenta que:
	• El script recibe los mismos parámetros que el del ejercicio 2:
	•• --camino: Es el directorio donde se encuentran las imágenes. Tener en cuenta que se deben
	renombrar todos los archivos, incluidos los de los subdirectorios.
	•• -p: Otra manera de nombrar a --camino. Se debe usar uno u otro.
	•• --dia: (Opcional) Es el nombre de un día para el cual no se quieren renombrar los archivos.
	Los valores posibles para este parámetro son los nombres de los días de la semana (sin 
	tildes). El script tiene que funcionar correctamente sin importar si el nombre del día está en
	minúsculas o mayúsculas.
	•• -d: Otra manera de nombrar a --dia. Se debe usar uno u otro
	• Como es una mejora sobre el script anterior, al ejecutarlo debe seguir renombrando los
	archivos existentes antes de quedar en modo monitoreo.
	• Durante el monitoreo, se debe devolver la terminal al usuario, es decir, el script debe correr
	en segundo plano como proceso demonio y no bloquear la terminal.
	• No se debe permitir la ejecución de más de una instancia del script al mismo tiempo.
	Para poder finalizar la ejecución del script, se debe agregar un parámetro “-k” que detendrá la
	ejecución del demonio. Se debe validar que este parámetro no se ingrese junto con el resto de los
	parámetros del script."
	exit 1
}

QANT=$#
RED='\033[0;31m'

if [[ $# -gt 4 ]]; then
	echo -e "${RED}ERROR: demasiados parametros"
	exit 1
fi

if [[ $# -eq 0 ]]; then
	echo -e "${RED}ERROR: ingrese parametros de ejecución (-h para instrucciones)"
	exit 1
fi


DIACHECK=0

while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
	-k)
		if [[ $QANT -gt 1 ]];	then
			echo -e "${RED}ERROR: Demasiados parametros para ejecutar $1"
			exit 1
		fi
		continue=1
		n=0
		declare -a arr
		while read p; do
				if [[ ! -z "$p" ]];then
					arr=("${arr[@]}" "$p")
					((n+=1))
				fi
		done <.APL1E3PIDlog
		while [[ $continue -eq 1 ]]; do
			echo "[0]Todos"
			x=1
			for i in "${arr[@]}"
			do
				echo "[$x]$i"
				((x+=1))
			done

			echo "Cual proceso desea terminar?:"
			read option
			while [[ $option -gt $n || $option -lt 0 ]];do
				echo "ERROR:Opción inválida, intente de nuevo:"
				read option
			done
			clear
			if [[ $option -eq 0 ]];then
				rm ".APL1E3PIDlog"
				pkill -f A1E3
				exit 1
			else
				((option-=1))
				process=$(echo ${arr[$option]} | awk '{print $1}')
				kill $process >/dev/null
				echo $process "terminado"
				((n-=1))
				unset 'arr[$option]'
				arr=("${arr[@]}")
				rm ".APL1E3PIDlog"
				printf "%s\n" "${arr[@]}" > .APL1E3PIDlog
			fi
			if [[ $n -eq 0 ]];then
				echo "No quedan procesos en ejecución"
				rm ".APL1E3PIDlog"
				exit
			fi
			echo "Quedan $n procesos, continuar?(Y/N): "
			read option
			clear
			while [[ "${option^^}" != @(N|Y) ]];do
				echo "ERROR:Opcion incorrecta, intente de nuevo: "
				read option
			done
			if [[ "${option^^}" = "N" ]];then
				if [[ $n -eq 0 ]];then
					rm ".APL1E3PIDlog"
				fi
				exit	
			fi
		done
		exit 1
	;;
	-p|--camino)
		if [[ -z $2 ]]; then
			echo -e "${RED}ERROR: Por favor ingrese un directorio junto con $1"
			exit 1
		fi
		if [[ -d $2 ]];	then
			camino=$2
			camino="$(realpath $camino)"
		else
			echo -e "${RED}ERROR: El directorio a procesar $2 no existe"
			exit 1	
		fi
		shift # past argument
		shift # past value
	;;
	-d|--dia)
		if [[ "${2^^}" != @(DOMINGO|LUNES|MARTES|MIERCOLES|JUEVES|VIERNES|SABADO|MIÉRCOLES|SÁBADO) ]]; then
			echo -e "${RED}ERROR: $2 no es un día de la semana"
			exit 1
		fi
		if [[ -z $2 ]]; then
			echo -e "${RED}ERROR: Por favor ingrese un día de la semana junto con $1"
			exit 1
		fi
		DIA="${2^^}"
		DIACHECK=1
		shift # past argument
		shift # past value
	;;
	-h|-help|-?)
		if [[ $QANT -gt 1 ]];	then
			echo -e "${RED}ERROR: Demasiados parametros para ejecutar $1"
			exit 1
		fi	
		mensaje_ayuda
		exit 1
	;;
	esac
done

if [[ -e ".APL1E3PIDlog" ]]; then
		while read p; do
			if [[ "$check" == "$camino }" ]];then
				echo -e "${RED}ERROR: El script ya esta en ejecución para ese directorio"
				exit 1
			fi
		done <.APL1E3PIDlog
fi

daemon(){
	while true; do
		while [ -z "$(ls $camino)" ]; do
			if false; then
				echo ""
			fi
		done
		for filename in $camino/*;do
			tiempo="Almuerzo"	
		
			aux="${filename%.*}"
			aux="${aux##*/}"
	
			if echo "$aux" | /bin/grep 'del' >/dev/null; then
				continue
			fi	
	
			yer=${aux:0:4}
			mes=${aux:4:2}
			dia=${aux:6:2}
		
			dow=$(/bin/date --date "$yer-$mes-$dia" +%u)
			dow=${dow^^}
			dow=$(traduccion $dow)
		
			if [[ DIACHECK -eq 1 && ${dow^^} == $DIA ]];then
					continue
			fi
	
		
			hora=${aux:9:2}
			minuto=${aux:11:2}
			segundo=${aux:13:2}
			if [[ $(( $hora*3600 + $minuto*60 + $segundo )) -gt 68400 ]];then
				tiempo="Cena"
			elif [[ $(( $hora*3600 + $minuto*60 + $segundo )) -lt 39600 ]];then
				tiempo="Desayuno"
			fi
			
			res="$dia-$mes-$yer $tiempo del $dow"
			/bin/mv "$filename" "$camino/$res.${filename##*.}" 
		done
	done
}

daemon &
echo "$! $camino" >> ".APL1E3PIDlog"